### PR TITLE
remove piracy in `hcat`, `vcat`, `hvcat`

### PR DESCRIPTION
**Pull request by ericphanson**
closes https://github.com/jump-dev/Convex.jl/issues/512

### CODE REVIEW

**Comment by odow** [comment]
I don't know that I like this approach.

Wouldn't it be better to force `Convex.hcat` and `Convex.vcat`?

Alternatively, this might work:
```julia
Base.hcat(args::AbstractExpr...) = HcatAtom(args...)

function Base.hcat(args::AbstractExprOrValue...)
    if all(Base.Fix2(isa, Value), args)
        return Base.cat(args..., dims = Val(2))
    end
    return HcatAtom(map(arg -> convert(AbstractExpr, arg), args)...)
end
```

**Comment by ericphanson** [comment]
I agree, this is unsatisfying. However: `Convex.hcat` doesn't allow use of the `[A B]` implicit hcat syntax which is often used in these problems. And I think
```julia
function Base.hcat(args::AbstractExprOrValue...)
    if all(Base.Fix2(isa, Value), args)
        return Base.cat(args..., dims = Val(2))
    end
    return HcatAtom(map(arg -> convert(AbstractExpr, arg), args)...)
end
```
is the same piracy as we are doing now, no? It's the method signature that matters for that, not what happens inside

**Comment by KristofferC** [comment]
Just FYI, these type of combinatorial method definition can lead to bad load times for the package (https://github.com/JuliaDiff/ReverseDiff.jl/issues/226).

**Comment by ericphanson** [comment]
Yeah, I noticed that when I initially chose `n=32` which never finished precompiling 😂. Do you have any ideas for how this can be improved?

I think the "right" fix is to be able to express "`Varags{Union{Value,AbstractExpr}}` but at least 1 `AbstractExpr`" in the type system, but I am guessing that isn't so easy to do.

**Comment by odow** [comment]
> is the same piracy as we are doing now, no?

Sort of, but to a lesser extent. Since `AbstractExprOrValue` is basically `Union{Number,AbstractVector,AbstractExpr}`, it should take lower precedence than the `Union{Number,AbstractVector}` method in Base.

**Pull request closed without merging**
