### PR TITLE
change `LogSumExp` atom to be per-column, for efficient `logisticloss`

### LINKED ISSUE #682: Scalar indexing in `logisticloss`
https://github.com/jump-dev/Convex.jl/blob/2978c32c0fcc3abc1cf10704980367cc23f8e1df/src/atoms/LogSumExpAtom.jl#L48

I guess I missed this one in #614

### PR DESCRIPTION
**Pull request by ericphanson**
closes #682 

the actual atom was never documented, only `logsumexp`, so this should be non-breaking

### CODE REVIEW

**Comment by odow** [comment]
Since this is a non-breaking performance issue, I think I'd prefer to come up with a standard way to represent `dims` arguments. So `dims = 0` is element-wise, `dims = 1` makes a row vector, and `dims = 2` makes a col vector.

We have quite a few hodgepodge elementwise/row/column conventions. It'd be useful to standardize.

**Comment by ericphanson** [comment]
I wonder if there's a lil abstraction we use, like
```julia
eachcol(x) = EachColAtom(x)
eachrow(x) = EachRowAtom(x)
```
and then these have slow IndexAtom based fallbacks, but we can sneak in optimizations like `logsumexp.(::EachColAtom)` lowering to something nice. (Either literally using broadcasting and hooking into the machinery there, or using `map` and regular dispatch etc).

**Comment by odow** [comment]
Yeah, I don't have a solution off the top of my head, but something like that. 

This is my main bugbear:
https://github.com/jump-dev/Convex.jl/blob/bce84a9620b093fc95a4c0daf9262d77f0f73aab/src/atoms/EntropyAtom.jl#L34-L36

**Comment by ericphanson** [comment]
closing in favor of #692

**Pull request closed without merging**
