### PR TITLE
Add OptimizationSenseAtom

### LINKED ISSUE #310: Partially specified problems
There was a post on discourse requesting partially specified problems: <https://discourse.julialang.org/t/convex-jl-trouble-with-partially-specified-function-inside-another-problem/26508/5>. There is also a good description in the CVX manual: http://web.cvxr.com/cvx/doc/advanced.html#new-functions-via-partially-specified-problems. I think this would be great, as it makes a very easy way to add new "atoms" (without actually having to make a struct, define methods, etc). I think it would work like this: the user (or someone implementing a new feature) defines a function which returns a problem, for example

```julia
function lamb_min(A::AbstractExpr)
    t = Variable()
    n = size(A, 1)
    n == size(A,2) || throw(ArgumentError())
    p = maximize(t, A - t*Matrix(1.0I, n, n) ⪰ 0)
    return p
end
```

Note: this is almost the actual implementation of the `lambdamin` atom: https://github.com/JuliaOpt/Convex.jl/blob/8a3e843d69c452ebeec80b24048a9a1e3efb84b9/src/atoms/sdp_cone/lambda_min_max.jl#L109-L110

This already works fine if I want to simply substitute some `AbstractExpr` into `lamb_min`; I could write

```julia
p = lambda_min(aff), constraints
solve!(p, solver)
```
for some affine expression `aff`. And if we wanted to be able to add additional constraints, we could pass those in as another argument to `lamb_min` (which is a bit clunky). But what if we want to substitute the result of `lamb_min` into another expression? E.g.

```julia
A = Variable(2,2)
p = maximize( lamb_min(A) + 1, [ A >= 0, A[1,1] == 2.0] )
```

Then we would like to treat `lamb_min(A)` as a `AbstractExpr` that evaluates to the solution to the inner problem. How do we do that?

1. Have `Problem` subtype `AbstractExpr`. To do so, we just need to add an `id_hash` and a `size`, and I believe add a `children` which yields the field `objective`. The `size` will always be `(1,1)`, so the latter two could be done by overriding `getproperty`.
2. Make sure `vexity(p::Problem)` means what it should for an `AbstractExpr`. Right now, if you minimize an affine function subject to affine constraints, `vexity(p)` will say `AffineVexity()` when it should be `ConvexVexity()` if it were to be treated as an `AbstractExpr`.
3. Make `conic_form!(p::Problem)` consistent with those for `AbstractExpr`. Right now it returns a hash in addition while other `conic_form!`'s do not.

Maybe some other things? That is about as far as I got. I'm not sure when I'll next have time to work on this, so I thought I'd write about it here as a feature request at least. I think it shouldn't be too hard to implement, but it will be important to make sure it's correct of course!

I think a good next step would be to try to document how the various `*conic*` functions work together to know how it should work (and what is treated different for a `Problem` than for an `AbstractExpr`).

Happy to hear any thoughts or if I've misunderstood something.

Note: I think atoms like `lambdamin` will still be useful-- I *think* that we wouldn't in general get `monotonicity` information (`monotonicity(lamb_min(A)) == NoMonotonicity()`), which we do know in this case. But we should be able to get `vexity` and `sign` (the sign of the objective function). So dedicated atoms like `lambda_min` would make sense still if you have monotonicity information, which we can't derive from the problem structure.  (I'm not sure if CVX can get monotonicity information somehow; if they can, maybe we can too).

It would be great if we could replace some atoms this way, though! We replaced the `partialtrace` atom with a simple function in https://github.com/JuliaOpt/Convex.jl/pull/284 and I think the code is cleaner for it.

### PR DESCRIPTION
**Pull request by odow**
Closes #310

### CODE REVIEW

**Comment by odow** [comment]
I don't know what's up with nightly

**Comment by blegat** [comment]
Looks good, maybe add some docstring for what this is used for ? IIUC, this is to get an error if we don't use it the right way, e.g.,
```julia
t = Variable()
add_constraint!(t, t >= x)
add_constraint!(t, t >= -x)
maximize(t)
```
Here, because we maximize `t`, our formulation does not yield the absolute value anymore
Now if you do
```julia
maximize(OptimizationSenseAtom(t, MOI.MIN_SENSE))
```
then you get an error saying it's not DCP because `t` is convex.

**Comment by ericphanson** [comment]
Looking at this more, I think in #504 I did a bunch of the parts to make this work with `Problems`, which gives us the nicer syntax of `minimize`/`maximize`, and potentially more natural places to put constraints:
```julia
using Convex, LinearAlgebra, Clarabel
using Convex: AbstractExpr

# monkeypatch the existing `getproperty`
function Base.getproperty(p::Problem, s::Symbol)
    if s === :optval
        if getfield(p, :status) == Convex.MOI.OPTIMIZE_NOT_CALLED
            return nothing
        else
            return Convex.objective_value(p)
        end
    elseif s === :size
        return p.objective.size
    end
    return getfield(p, s)
end

function lamb_min(A::AbstractExpr)
    t = Variable()
    n = size(A, 1)
    n == size(A,2) || throw(ArgumentError())
    p = maximize(t, A - t*Matrix(1.0I, n, n) ⪰ 0)
    return p
end

p = maximize( lamb_min(A) + 1, [ A >= 0, A[1,1] == 2.0] )

solve!(p, Clarabel.Optimizer)
```

```julia
julia> print(p.model)
Maximize ScalarAffineFunction{Float64}:
 1.0 + 1.0 v[5]

Subject to:

VectorAffineFunction{Float64}-in-Zeros
 ┌               ┐
 │-2.0 + 1.0 v[1]│
 └               ┘ ∈ Zeros(1)

VectorAffineFunction{Float64}-in-Nonnegatives
 ┌              ┐
 │0.0 + 1.0 v[1]│
 │0.0 + 1.0 v[2]│
 │0.0 + 1.0 v[3]│
 │0.0 + 1.0 v[4]│
 └              ┘ ∈ Nonnegatives(4)

VectorAffineFunction{Float64}-in-PositiveSemidefiniteConeSquare
 ┌                                    ┐
 │0.0 + 1.0 v[1] - 1.0 v[5]           │
 │0.0 + 1.0 v[3] + 1.0 v[2] - 1.0 v[3]│
 │0.0 + 1.0 v[3]                      │
 │0.0 + 1.0 v[4] - 1.0 v[5]           │
 └                                    ┘ ∈ PositiveSemidefiniteConeSquare(2)
```

However, it's not fully correct yet, since if I flip `maximize` to `minimize` in the definition of `lamb_min` I don't get an error.

IMO if we get this working, it will be easier for users than introducing a new atom.

**Comment by odow** [comment]
Okay let me take a look

**Comment by odow** [comment]
Closing for now. I'll take another shot at this.

**Pull request closed without merging**
